# fly.toml app configuration file generated for matcharestockchecker on 2025-03-17T01:22:30-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'matcharestockchecker'
primary_region = 'dfw'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
