name: Matcha Restock Checker

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:       # Allow manual runs

jobs:
  check-restock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download previous stock status artifact (if it exists)
        uses: actions/download-artifact@v4
        continue-on-error: true  # Avoid failing if artifact doesn't exist yet
        with:
          name: stock_status  # Must match the name used during upload
          path: stock_status.json

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Matcha Restock script
        env:
          IPPUDO_URL: ${{ secrets.IPPUDO_URL }}
          MATCHA_JP_URL: ${{ secrets.MATCHA_JP_URL }}
          SAZEN_URLS: ${{ secrets.SAZEN_URLS }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          RECIPIENT_SMS: ${{ secrets.RECIPIENT_SMS }}
        run: |
          python main.py

      - name: Upload updated stock status artifact
        uses: actions/upload-artifact@v4
        with:
          name: stock_status
          path: stock_status.json
