name: Matcha Restock Checker

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:       # Manual trigger

permissions:
  contents: write  # Required for pushing with GITHUB_TOKEN

jobs:
  check-restock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure stock_status.json exists
        run: |
          if [ ! -f "stock_status.json" ]; then
            echo "{}" > stock_status.json
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Matcha Restock script
        env:
          IPPUDO_URL: ${{ secrets.IPPUDO_URL }}
          MATCHA_JP_URL: ${{ secrets.MATCHA_JP_URL }}
          SAZEN_URLS: ${{ secrets.SAZEN_URLS }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          RECIPIENT_SMS: ${{ secrets.RECIPIENT_SMS }}
        run: |
          python main.py

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Check if stock_status.json changed
        id: status-check
        run: |
          git fetch origin
          if git diff --quiet stock_status.json; then
            echo "No changes to commit."
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected."
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push updated stock_status.json
        if: steps.status-check.outputs.changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add stock_status.json
          git commit -m "Update stock_status.json [CI auto-update]"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
