name: Matcha Restock Checker

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:

jobs:
  check-restock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Try download previous stock status artifact
        continue-on-error: true  # Don't fail if not found
        uses: actions/download-artifact@v4
        with:
          name: stock-status
          path: .

      - name: Run script
        env:
          IPPUDO_URL: ${{ secrets.IPPUDO_URL }}
          MATCHA_JP_URL: ${{ secrets.MATCHA_JP_URL }}
          SAZEN_URLS:  ${{ secrets.SAZEN_URLS }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          RECIPIENT_SMS: ${{ secrets.RECIPIENT_SMS }}
        run: |
          python main.py

      - name: Upload updated stock status artifact
        uses: actions/upload-artifact@v4
        with:
          name: stock-status
          path: stock_status.json
          overwrite: true
